import 'package:movie_app/data/vos/actor_vo.dart';
import 'package:movie_app/data/vos/credit_vo.dart';
import 'package:movie_app/data/vos/genre_vo.dart';
import 'package:movie_app/data/vos/movie_vo.dart';

List<MovieVO> getMockMoviesForTest() {
  return [
    MovieVO(
        index: 19,
        adult: false,
        backDropPath: null,
        genreIds: [28, 12, 14, 878],
        id: 19995,
        originalLanguage: "en",
        originalTitle: "Avatar",
        overview:
            "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.",
        popularity: 729.976,
        posterPath: " /jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg",
        releaseDate: DateTime.parse("2009-12-15 00:00:00.000"),
        title: "Avatar",
        video: false,
        voteAverage: 7.5,
        budget: null,
        voteCount: 26483,
        belongsToCollection: null,
        genres: null,
        homepage: null,
        imdbid: null,
        productionCompany: null,
        productionCountry: null,
        revenue: null,
        runtime: null,
        spokenLanguages: null,
        status: null,
        tagline: null,
        isNowPlaying: true,
        isPopular: false,
        isTopRated: false),
    MovieVO(
        index: 8,
        adult: false,
        backDropPath: null,
        genreIds: [80, 18, 9648, 53],
        id: 848791,
        originalLanguage: "en",
        originalTitle: "The Stranger",
        overview:
            "Two strangers strike up a conversation on a long journey. One is a suspect in an unsolved missing person’s case and the other an undercover operative on his trail. Their uneasy friendship becomes the core of this tightly wrought thriller, which is based on the true story of one of the largest investigations and undercover operations in Australia.",
        popularity: 1026.413,
        posterPath: "/ydbm5Ad1nyZq7eywWsw82Wxdsgg.jpg",
        releaseDate: DateTime.parse("2022-10-06 00:00:00.000"),
        title: "The Stranger",
        video: false,
        voteAverage: 6.1,
        budget: null,
        voteCount: 98,
        belongsToCollection: null,
        genres: null,
        homepage: null,
        imdbid: null,
        productionCompany: null,
        productionCountry: null,
        revenue: null,
        runtime: null,
        spokenLanguages: null,
        status: null,
        tagline: null,
        isNowPlaying: true,
        isPopular: false,
        isTopRated: false),
    MovieVO(
        index: 13,
        adult: false,
        backDropPath: null,
        genreIds: [27, 9648, 53],
        id: 882598,
        originalLanguage: "en",
        originalTitle: " Smile",
        overview:
            "After witnessing a bizarre, traumatic incident involving a patient, Dr. Rose Cotter starts experiencing frightening occurrences that she can't explain. As an overwhelming terror begins taking over her life, Rose must confront her troubling past in order to survive and escape her horrifying new reality.",
        popularity: 710.014,
        posterPath: "/aPqcQwu4VGEewPhagWNncDbJ9Xp.jpg",
        releaseDate: DateTime.parse("2022-09-23 00:00:00.000"),
        title: "Smile",
        video: false,
        voteAverage: 6.8,
        budget: null,
        voteCount: 447,
        belongsToCollection: null,
        genres: null,
        homepage: null,
        imdbid: null,
        productionCompany: null,
        productionCountry: null,
        revenue: null,
        runtime: null,
        spokenLanguages: null,
        status: null,
        tagline: null,
        isNowPlaying: true,
        isPopular: false,
        isTopRated: false),
  ];
}

List<ActorVO> getMockActors() {
  return [
    ActorVO(
      id: 3194176,
      adult: false,
      knownFor: [],
      name: " Angeli Khang",
      profilePath: " /jhNtIfmSlzsyQlo94BibQ2WIa7N.jpg",
      popularity: 183.07,
    ),
    ActorVO(
      id: 125025,
      adult: false,
      knownFor: [],
      name: "Joey King",
      profilePath: "/kL0lWLJA6lbvmPM3YL0ISE6rVr6.jpg",
      popularity: 157.976,
    ),
    ActorVO(
      id: 1907997,
      adult: false,
      knownFor: [],
      name: "Min Do-yoon",
      profilePath: "/bHHn3krbHyxQIWb4JbHkPlV6Uu1.jpg",
      popularity: 154.808,
    ),
    ActorVO(
      id: 1292329,
      adult: false,
      knownFor: [],
      name: " Kimberley Sustad",
      profilePath: "/w6LpI0W09gvGqthPvVBwCf3WF6c.jpg",
      popularity: 133.669,
    ),
    ActorVO(
      id: 1356210,
      adult: false,
      knownFor: [],
      name: "Millie Bobby Brown",
      profilePath: "/2685xGmq68G6tmnUbfgSR6rywEV.jpg",
      popularity: 131.374,
    ),
  ];
}

List<GenreVO> getMockGenre() {
  return [
    GenreVO(id: 1, name: "Action"),
    GenreVO(id: 2, name: "Adventure"),
    GenreVO(id: 3, name: "Comedy"),
  ];
}

List<CreditVO> getMockCredits() {
  return [
    CreditVO(
      adult: false,
      gender: 1,
      id: 1882502,
      konwnForDepartment: "Acting",
      name: "Lauren LaVera",
      originalName: "Lauren LaVera",
      profilePath: "/wrVoBR5YhdEcadqwPICkcXXTbWk.jpg",
      castId: 3,
      character: "Sienna",
      creditId: "5f69c113688cd000361d4090",
      order: 0,
    ),
    CreditVO(
      adult: false,
      gender: 2,
      id: 1880016,
      konwnForDepartment: "Acting",
      name: "David Howard Thornton",
      originalName: "David Howard Thornton",
      profilePath: "/z82y3Nxm7VZjfaMPMdUtbyoAyls.jpg",
      castId: 1,
      character: "Art the Clown",
      creditId: "5e1db04ee194b00012b9be1a",
      order: 1,
    ),
    CreditVO(
      adult: false,
      gender: 0,
      id: 2787720,
      konwnForDepartment: "Acting",
      name: "Elliott Fullam",
      originalName: "Elliott Fullam",
      profilePath: "/qEImB0krCVblSAD7xz67s0bvBRQ.jpg",
      castId: 9,
      character: "Jonathan",
      creditId: "5f69c244c4ad590039fa8d63",
      order: 2,
    ),
    CreditVO(
      adult: false,
      gender: 1,
      id: 3383606,
      konwnForDepartment: "Acting",
      name: "Sarah Voigt",
      originalName: "Sarah Voigt",
      profilePath: null,
      castId: 72,
      character: "Barbara",
      creditId: "635222cd4ca676007fe394f7",
      order: 3,
    ),
  ];
}
