const MAIN_SCREEN_APP_BAR_TITLE = 'Discover';
const MAIN_SCREEN_BEST_POPULAR_MOVIE_AND_SCREEN =
    'BEST POPULAR MOVIES AND SERIALS';
const MAIN_SCREEN_SEE_MORE = 'SEE MORE';
const MAIN_SCREEN_CHECK_MOVIE_SHOW_TIME = 'Check Movie\nShowtimes';
const SHOW_CASES_TITLE = "SHOWCASES";
const SHOW_CASE_SEE_MORE = 'MORE SHOWCASES';
const BEST_ACTOR_TITLE = 'BEST ACTOR';
const BEST_ACTOR_SEE_MORE = "MORE ACTORS";

const MOVIE_DETAILS_SCREEN_ACTORS_TITLE = 'ACOTRS';
const MOVIE_DETAILS_SCREEN_CREATORS_TITLE = 'CREATORS';
const MOVIE_DETAILS_SCREEN_CREATORS_SEE_MORE = 'MORE CREATORS';
const MOVIE_DETAILS_SCREEN_STORE_LINE_TITLE = 'STORELINE';
const MOVIE_DETAILS_SCREEN_RELEATED_MOVIE = 'Related Movie';
