// Hive Type
const int HIVE_TYPE_ID_ACTOR_VO = 1;
const int HIVE_TYPE_ID_BASE_ACTOR_VO = 2;
const int HIVE_TYPE_ID_COLLECTION_VO = 3;
const int HIVE_TYPE_ID_CREDIT_VO = 4;
const int HIVE_TYPE_ID_DATE_VO = 5;
const int HIVE_TYPE_ID_GENRE_VO = 6;
const int HIVE_TYPE_ID_MOVIE_VO = 7;
const int HIVE_TYPE_ID_PORDUCTION_COMPANY_VO = 8;
const int HIVE_TYPE_ID_PORDUCTION_COUNTRY_VO = 9;
const int HIVE_TYPE_ID_SPOKEN_LANGUAGE_VO = 10;

// Box Name
const String BOX_NAME_ACTOR_VO = 'BOX_NAME_ACTOR_VO';
const String BOX_NAME_BASE_ACTOR_VO = 'BOX_NAME_BASE_ACTOR_VO';
const String BOX_NAME_COLLECTION_VO = 'BOX_NAME_COLLECTION_VO';
const String BOX_NAME_CREDIT_VO = 'BOX_NAME_CREDIT_VO';
const String BOX_NAME_DATE_VO = 'BOX_NAME_DATE_VO';
const String BOX_NAME_GENRE_VO = 'BOX_NAME_GENRE_VO';
const String BOX_NAME_MOVIE_VO = 'BOX_NAME_MOVIE_VO';
const String BOX_NAME_PRODUCTION_COMPANY_VO = 'BOX_NAME_PRODUCTION_COMPANY_VO';
const String BOX_NAME_PRODUCTION_COUNTRY_VO = 'BOX_NAME_PRODUCTION_COUNTRY_VO';
const String BOX_NAME_SPOKEN_LANGUAGE_VO = 'BOX_NAME_SPOKEN_LANGUAGE_VO';
